Le but de l'exercice est d'expliquer à travers les speed dating de 4 minutes, en quoi les gens sont attirés par les autres.
Après le speed dating, on demande aux participants si ils veulent revoir le partenaire ou non et de noter le partenaire selon ces critères :
- attractivité
- sincérité
- intelligence
- fun
- ambition
- intérêts partagés

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("Speed_Dating_Data.csv")

In [ ]:
#Nous allons regarder à quoi ressemble le dataset

In [ ]:
df.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,tuition,mn_sat,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
noms_colonnes = df.columns.tolist()
print(noms_colonnes)

['iid', 'id', 'gender', 'idg', 'condtn', 'wave', 'round', 'position', 'positin1', 'order', 'partner', 'pid', 'match', 'int_corr', 'samerace', 'age_o', 'race_o', 'pf_o_att', 'pf_o_sin', 'pf_o_int', 'pf_o_fun', 'pf_o_amb', 'pf_o_sha', 'dec_o', 'attr_o', 'sinc_o', 'intel_o', 'fun_o', 'amb_o', 'shar_o', 'like_o', 'prob_o', 'met_o', 'age', 'field', 'field_cd', 'undergra', 'tuition', 'mn_sat', 'race', 'imprace', 'imprelig', 'from', 'zipcode', 'income', 'goal', 'date', 'go_out', 'career', 'career_c', 'sports', 'tvsports', 'exercise', 'dining', 'museums', 'art', 'hiking', 'gaming', 'clubbing', 'reading', 'tv', 'theater', 'movies', 'concerts', 'music', 'shopping', 'yoga', 'exphappy', 'expnum', 'attr1_1', 'sinc1_1', 'intel1_1', 'fun1_1', 'amb1_1', 'shar1_1', 'attr4_1', 'sinc4_1', 'intel4_1', 'fun4_1', 'amb4_1', 'shar4_1', 'attr2_1', 'sinc2_1', 'intel2_1', 'fun2_1', 'amb2_1', 'shar2_1', 'attr3_1', 'sinc3_1', 'fun3_1', 'intel3_1', 'amb3_1', 'attr5_1', 'sinc5_1', 'intel5_1', 'fun5_1', 'amb5_1', 'dec', 'attr', 'sinc', 'intel', 'fun', 'amb', 'shar', 'like', 'prob', 'met', 'match_es', 'attr1_s', 'sinc1_s', 'intel1_s', 'fun1_s', 'amb1_s', 'shar1_s', 'attr3_s', 'sinc3_s', 'intel3_s', 'fun3_s', 'amb3_s', 'satis_2', 'length', 'numdat_2', 'attr7_2', 'sinc7_2', 'intel7_2', 'fun7_2', 'amb7_2', 'shar7_2', 'attr1_2', 'sinc1_2', 'intel1_2', 'fun1_2', 'amb1_2', 'shar1_2', 'attr4_2', 'sinc4_2', 'intel4_2', 'fun4_2', 'amb4_2', 'shar4_2', 'attr2_2', 'sinc2_2', 'intel2_2', 'fun2_2', 'amb2_2', 'shar2_2', 'attr3_2', 'sinc3_2', 'intel3_2', 'fun3_2', 'amb3_2', 'attr5_2', 'sinc5_2', 'intel5_2', 'fun5_2', 'amb5_2', 'you_call', 'them_cal', 'date_3', 'numdat_3', 'num_in_3', 'attr1_3', 'sinc1_3', 'intel1_3', 'fun1_3', 'amb1_3', 'shar1_3', 'attr7_3', 'sinc7_3', 'intel7_3', 'fun7_3', 'amb7_3', 'shar7_3', 'attr4_3', 'sinc4_3', 'intel4_3', 'fun4_3', 'amb4_3', 'shar4_3', 'attr2_3', 'sinc2_3', 'intel2_3', 'fun2_3', 'amb2_3', 'shar2_3', 'attr3_3', 'sinc3_3', 'intel3_3', 'fun3_3', 'amb3_3', 'attr5_3', 'sinc5_3', 'intel5_3', 'fun5_3', 'amb5_3']

In [ ]:
#Nous voyons qu'il y a des colonnes avec des valeurs NaN, nous allons donc les remplacer les supprimer

In [ ]:
df = df.dropna(axis=1, how='all')

In [ ]:
df.describe()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field_cd,race,imprace,imprelig,goal,date,go_out,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,8378.000000,8368.000000,8378.000000,8220.000000,8378.000000,8274.000000,8305.000000,8289.000000,8289.000000,8289.000000,8280.000000,8271.000000,8249.000000,8378.000000,8166.000000,8091.000000,8072.000000,8018.000000,7656.000000,7302.000000,8128.000000,8060.000000,7993.000000,8283.000000,8296.000000,8315.000000,8299.000000,8299.000000,8299.000000,8281.000000,8299.000000,8240.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8277.000000,1800.000000,8299.000000,8299.000000,8299.000000,8289.000000,8279.000000,8257.000000,6489.000000,6489.000000,6489.000000,6489.000000,6489.000000,6467.000000,8299.000000,8299.000000,8299.000000,8299.000000,8289.000000,8289.000000,8273.000000,8273.000000,8273.000000,8273.000000,8273.000000,4906.000000,4906.000000,4906.000000,4906.000000,4906.000000,8378.000000,8176.000000,8101.000000,8082.000000,8028.000000,7666.000000,7311.000000,8138.000000,8069.000000,8003.000000,7205.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,7463.000000,7463.000000,7433.000000,1984.000000,1955.000000,1984.000000,1984.000000,1955.000000,1974.000000,7445.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.00000,5775.000000,5775.000000,5775.000000,5775.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,4377.000000,4377.000000,4377.000000,4377.000000,4377.000000,3974.000000,3974.000000,3974.000000,1496.000000,668.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2016.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,8.963595,283.863767,0.164717,0.196010,0.395799,26.364999,2.756653,22.495347,17.396867,20.270759,17.459714,10.685375,11.845930,0.419551,6.190411,7.175256,7.369301,6.400599,6.778409,5.474870,6.134498,5.208251,1.960215,26.358928,7.662488,2.757186,3.784793,3.651645,2.122063,5.006762,2.158091,5.277791,6.425232,4.575491,6.245813,7.783829,6.985781,6.714544,5.737077,3.881191,5.745993,7.678515,5.304133,6.776118,7.919629,6.825401,7.851066,5.631281,4.339197,5.534131,5.570556,22.514632,17.396389,20.265613,17.457043,10.682539,11.845111,26.394360,11.071506,12.636308,15.566805,9.780089,11.014845,30.362192,13.273691,14.416891,18.422620,11.744499,11.854817,7.084733,8.294935,7.704460,8.403965,7.578388,6.941908,7.927232,8.284346,7.426213,7.617611,0.419909,6.189995,7.175164,7.368597,6.400598,6.777524,5.474559,6.134087,5.207523,0.948769,3.207814,20.791624,15.434255,17.243708,15.260869,11.144619,12.457925,7.21125,8.082000,8.257750,7.692500,7.589250,5.711510,1.843495,2.338087,32.819556,13.529923,15.293851,18.868448,7.286957,12.156028,26.217194,15.865084,17.813755,17.654765,9.913436,12.760263,26.806234,11.929177,12.103030,15.163810,9.342511,11.320866,29.344369,13.89823,13.958265,17.967233,11.909735,12.887976,7.125285,7.931529,8.238912,7.602171,7.486802,6.827964,7.394106,7.838702,7.279415,7.332191,0.780825,0.981631,0.376950,1.230615,0.934132,24.384524,16.588583,19.411346,16.233415,10.898075,12.699142,31.330357,15.654266,16.679563,16.418155,7.823909,12.207837,25.610341,10.751267,11.524839,14.276783,9.207503,11.253802,24.970936,10.923285,11.952687,14.959108,9.526191,11.966270,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,5.491068,158.584899,0.370947,0.303539,0.489051,3.563648,1.230689,12.569802,7.044003,6.782895,6.085526,6.126544,6.362746,0.493515,1.950305,1.740575,1.550501,1.954078,1.794080,2.156163,1.841258,2.129354,0.245925,3.566763,3.758935,1.230905,2.845708,2.805237,1.407181,1.444531,1.105246,3.309520,2.619024,2.801874,2.418858,1.754868,2.052232,2.263407,2.570207,2.620507,2.502218,2.006565,2.529135,2.235152,1.700927,2.156283,1.791827,2.608913,2.717612,1.734059,4.762569,12.587674,7.046700,6.783003,6.085239,6.124888,6.362154,16.297045,6.659233,6.717476,7.328256,6.998428,6.060150,16.249937,6.976775,6.263304,6.577929,6.886532,6.167314,1.395783,1.407460,1.564321,1.076608,1.778315,1.498653,1.627054,1.283657,1.779129,1.773094,0.493573,1.950169,1.740315,1.550453,1.953702,1.794055,2.156363,1.841285,2.129565,0.989889,2.444813,12.968524,6.915322,6.596420,5.356969,5.514028,5.921789,1.41545,1.455741,1.179317,1.626839,1.793136,1.820764,0.975662,0.631240,17.155270,7.977482,7.292868,8.535963,6.125187,8.241906,14.388694,6.658494,6.535894,6.129746,5.675550,6.651547,16.402836,6.401556,5.990607,7.290107,5.856329,6.296155,14.551171,6.17169,5.398621,6.100307,6.313281,5.615691,1.371390,1.503236,1.180280,1.548200,1.744634,1.411096,1.588145,1.280936,1.647478,1.521854,1.611694,1.382139,0.484683,1.294557,0.753902,13.712120,7.471537,6.124502,5.163777,5.900697,6.557041,17.551540,9.336288,7.880088,7.231325,6.100502,8.615985,17.477134,5.740351,6.004222,6.927869,6.385852,6.516178,17.007669,6.226283,7.010650,7.935509,6.403117,7.012067,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-0.830000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.00000,1.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,4.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,4.000000,154.000000,0.000000,-0.020000,0.000000,24.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,2.000000,24.000000,5.000000,2.000000,1.000000,1.000000,1.000000,4.000000,1.000000,2.000000,4.000000,2.000000,5.000000,7.000000,6.000000,5.000000,4.000000,2.000000,4.000000,7.000000,3.000000,5.000000,7.000000,5.000000,7.000000,4.000000,2.000000,5.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,10.000000,6.000000,8.000000,10.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,6.000000,10.000000,6.000000,8.000000,7.000000,8.000000,7.000000,6.000000,7.000000,8.000000,6.000000,7.000000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,14.810000,10.000000,10.000000,10.000000,7.000000,9.000000,7.00000,7.000000,8.000000,7.000000,7.000000,5.000000,1.000000,2.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,16.670000,10.000000,15.000000,15.000000,5.000000,10.000000,10.000000,8.000000,8.000000,9.000000,5.000000,7.000000,19.150000,10.00000,10.000000,15.000000,10.000000,10.000000,7.000000,7.000000,8.000000,7.000000,7.000000,6.000000,6.000000,7.000000,6.000000,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,15.220000,10.000000,16.670000,14.810000,5.000000,10.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,10.000000,7.000000,7.000000,9.000000,5.000000,7.000000,10.000000,7.000000,7.000000,9.000000,6.000000,5.000000,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,8.000000,281.000000,0.000000,0.210000,0.000000,26.000000,2.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.640000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,2.000000,26.000000,8.000000,2.000000,3.000000,3.000000,2.000000,5.000000,2.000000,6.000000,7.000000,4.000000,6.000000,8.000000,7.000000,7.000000,6.000000,3.000000,6.000000,8.000000,6.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,6.000000,4.000000,20.000000,18.180000,20.000000,18.000000,10.000000,10.640000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.000000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,0.000000,3.000000,17.650000,15.790000,18.420000,15.910000,10.000000,12.500000,7.00000,8.000000,8.000000,8.000000,8.000000,6.000000,1.000000,2.000000,30.000000,10.000000,15.000000,20.000000,5.000000,10.000000,20.000000,16.670000,19.050000,18.370000,10.000000,13.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.00000,15.000000,18.520000,10.000000,13.950000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000,0.000000,1.000000,0.000000,1.000000,1.000000,20.000000,16.670000,20.000000,16.330000,10.000000,14.290000,25.000000,15.000000,18.000000,17.000000,10.000000,10.000000,20.000000,10.000000,10.000000,12.000000,9.000000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,13.000000,408.000000,0.000000,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,28.000000,10.000000,4.000000,6.000000,6.000000,2.000000,6.000000,3.000000,7.000000,9.000000,7.000000,8.000000,9.000000,9.000000,8.000000,8.000000,6.000000,8.000000,9.000000,7.000000,9.000000,9.000000,8.000000,9.000000,8.000000,7.000000,7.000000,8.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,35.000000,15.000000,16.000000,20.000000,15.000000,15.000000,40.000000,18.750000,20.000000,20.000000,15.000000,15.630000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,4.000000,25.000000,20.000000,20.000000,20.000000,15.000000,16.280000,8.00000,9.000000,9.000000,9.000000,9.000000,7.000000,3.000000,3.000000,40.000000,20.000000,20.000000,24.000000,10.000000,20.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,15.000000,15.000000,20.000000,10.000000,15.000000,38.460000,19.23000,17.390000,20.000000,15.090000,16.515000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,20.000000,20.000000,20.000000,10.000000,20.000000,37.000000,15.000000,15.000000,20.000000,10.000000,15.000000,35.000000,15.000000,15.000000,20.000000,10.000000,15.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,22.000000,552.000000,1.000000,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,1.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,8.000000,55.000000,18.000000,6.000000,10.000000,10.000000,6.000000,7.000000,7.000000,17.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,20.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,18.000000,95.000000,50.000000,40.000000,40.000000,23.810000,30.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,3.000000,80.000000,40.000000,50.000000,50.000000,20.000000,40.000000,85.000000,50.000000,40.000000,50.000000,22.220000,35.000000,100.000000,35.000000,40.000000,50.000000,35.000000,40.000000,85.000000,40.00000,30.770000,40.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.000000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [ ]:
#Nous voyons qu'il y a une virgule qui ne nous sert pas nous allons l'enlever

In [ ]:
df.describe()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field_cd,race,imprace,imprelig,goal,date,go_out,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,8378.000000,8368.000000,8378.000000,8220.000000,8378.000000,8274.000000,8305.000000,8289.000000,8289.000000,8289.000000,8280.000000,8271.000000,8249.000000,8378.000000,8166.000000,8091.000000,8072.000000,8018.000000,7656.000000,7302.000000,8128.000000,8060.000000,7993.000000,8283.000000,8296.000000,8315.000000,8299.000000,8299.000000,8299.000000,8281.000000,8299.000000,8240.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8277.000000,1800.000000,8299.000000,8299.000000,8299.000000,8289.000000,8279.000000,8257.000000,6489.000000,6489.000000,6489.000000,6489.000000,6489.000000,6467.000000,8299.000000,8299.000000,8299.000000,8299.000000,8289.000000,8289.000000,8273.000000,8273.000000,8273.000000,8273.000000,8273.000000,4906.000000,4906.000000,4906.000000,4906.000000,4906.000000,8378.000000,8176.000000,8101.000000,8082.000000,8028.000000,7666.000000,7311.000000,8138.000000,8069.000000,8003.000000,7205.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,7463.000000,7463.000000,7433.000000,1984.000000,1955.000000,1984.000000,1984.000000,1955.000000,1974.000000,7445.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.00000,5775.000000,5775.000000,5775.000000,5775.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,4377.000000,4377.000000,4377.000000,4377.000000,4377.000000,3974.000000,3974.000000,3974.000000,1496.000000,668.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2016.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,8.963595,283.863767,0.164717,0.196010,0.395799,26.364999,2.756653,22.495347,17.396867,20.270759,17.459714,10.685375,11.845930,0.419551,6.190411,7.175256,7.369301,6.400599,6.778409,5.474870,6.134498,5.208251,1.960215,26.358928,7.662488,2.757186,3.784793,3.651645,2.122063,5.006762,2.158091,5.277791,6.425232,4.575491,6.245813,7.783829,6.985781,6.714544,5.737077,3.881191,5.745993,7.678515,5.304133,6.776118,7.919629,6.825401,7.851066,5.631281,4.339197,5.534131,5.570556,22.514632,17.396389,20.265613,17.457043,10.682539,11.845111,26.394360,11.071506,12.636308,15.566805,9.780089,11.014845,30.362192,13.273691,14.416891,18.422620,11.744499,11.854817,7.084733,8.294935,7.704460,8.403965,7.578388,6.941908,7.927232,8.284346,7.426213,7.617611,0.419909,6.189995,7.175164,7.368597,6.400598,6.777524,5.474559,6.134087,5.207523,0.948769,3.207814,20.791624,15.434255,17.243708,15.260869,11.144619,12.457925,7.21125,8.082000,8.257750,7.692500,7.589250,5.711510,1.843495,2.338087,32.819556,13.529923,15.293851,18.868448,7.286957,12.156028,26.217194,15.865084,17.813755,17.654765,9.913436,12.760263,26.806234,11.929177,12.103030,15.163810,9.342511,11.320866,29.344369,13.89823,13.958265,17.967233,11.909735,12.887976,7.125285,7.931529,8.238912,7.602171,7.486802,6.827964,7.394106,7.838702,7.279415,7.332191,0.780825,0.981631,0.376950,1.230615,0.934132,24.384524,16.588583,19.411346,16.233415,10.898075,12.699142,31.330357,15.654266,16.679563,16.418155,7.823909,12.207837,25.610341,10.751267,11.524839,14.276783,9.207503,11.253802,24.970936,10.923285,11.952687,14.959108,9.526191,11.966270,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,5.491068,158.584899,0.370947,0.303539,0.489051,3.563648,1.230689,12.569802,7.044003,6.782895,6.085526,6.126544,6.362746,0.493515,1.950305,1.740575,1.550501,1.954078,1.794080,2.156163,1.841258,2.129354,0.245925,3.566763,3.758935,1.230905,2.845708,2.805237,1.407181,1.444531,1.105246,3.309520,2.619024,2.801874,2.418858,1.754868,2.052232,2.263407,2.570207,2.620507,2.502218,2.006565,2.529135,2.235152,1.700927,2.156283,1.791827,2.608913,2.717612,1.734059,4.762569,12.587674,7.046700,6.783003,6.085239,6.124888,6.362154,16.297045,6.659233,6.717476,7.328256,6.998428,6.060150,16.249937,6.976775,6.263304,6.577929,6.886532,6.167314,1.395783,1.407460,1.564321,1.076608,1.778315,1.498653,1.627054,1.283657,1.779129,1.773094,0.493573,1.950169,1.740315,1.550453,1.953702,1.794055,2.156363,1.841285,2.129565,0.989889,2.444813,12.968524,6.915322,6.596420,5.356969,5.514028,5.921789,1.41545,1.455741,1.179317,1.626839,1.793136,1.820764,0.975662,0.631240,17.155270,7.977482,7.292868,8.535963,6.125187,8.241906,14.388694,6.658494,6.535894,6.129746,5.675550,6.651547,16.402836,6.401556,5.990607,7.290107,5.856329,6.296155,14.551171,6.17169,5.398621,6.100307,6.313281,5.615691,1.371390,1.503236,1.180280,1.548200,1.744634,1.411096,1.588145,1.280936,1.647478,1.521854,1.611694,1.382139,0.484683,1.294557,0.753902,13.712120,7.471537,6.124502,5.163777,5.900697,6.557041,17.551540,9.336288,7.880088,7.231325,6.100502,8.615985,17.477134,5.740351,6.004222,6.927869,6.385852,6.516178,17.007669,6.226283,7.010650,7.935509,6.403117,7.012067,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-0.830000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.00000,1.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,4.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,4.000000,154.000000,0.000000,-0.020000,0.000000,24.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,2.000000,24.000000,5.000000,2.000000,1.000000,1.000000,1.000000,4.000000,1.000000,2.000000,4.000000,2.000000,5.000000,7.000000,6.000000,5.000000,4.000000,2.000000,4.000000,7.000000,3.000000,5.000000,7.000000,5.000000,7.000000,4.000000,2.000000,5.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,10.000000,6.000000,8.000000,10.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,6.000000,10.000000,6.000000,8.000000,7.000000,8.000000,7.000000,6.000000,7.000000,8.000000,6.000000,7.000000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,14.810000,10.000000,10.000000,10.000000,7.000000,9.000000,7.00000,7.000000,8.000000,7.000000,7.000000,5.000000,1.000000,2.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,16.670000,10.000000,15.000000,15.000000,5.000000,10.000000,10.000000,8.000000,8.000000,9.000000,5.000000,7.000000,19.150000,10.00000,10.000000,15.000000,10.000000,10.000000,7.000000,7.000000,8.000000,7.000000,7.000000,6.000000,6.000000,7.000000,6.000000,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,15.220000,10.000000,16.670000,14.810000,5.000000,10.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,10.000000,7.000000,7.000000,9.000000,5.000000,7.000000,10.000000,7.000000,7.000000,9.000000,6.000000,5.000000,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,8.000000,281.000000,0.000000,0.210000,0.000000,26.000000,2.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.640000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,2.000000,26.000000,8.000000,2.000000,3.000000,3.000000,2.000000,5.000000,2.000000,6.000000,7.000000,4.000000,6.000000,8.000000,7.000000,7.000000,6.000000,3.000000,6.000000,8.000000,6.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,6.000000,4.000000,20.000000,18.180000,20.000000,18.000000,10.000000,10.640000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.000000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,0.000000,3.000000,17.650000,15.790000,18.420000,15.910000,10.000000,12.500000,7.00000,8.000000,8.000000,8.000000,8.000000,6.000000,1.000000,2.000000,30.000000,10.000000,15.000000,20.000000,5.000000,10.000000,20.000000,16.670000,19.050000,18.370000,10.000000,13.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.00000,15.000000,18.520000,10.000000,13.950000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000,0.000000,1.000000,0.000000,1.000000,1.000000,20.000000,16.670000,20.000000,16.330000,10.000000,14.290000,25.000000,15.000000,18.000000,17.000000,10.000000,10.000000,20.000000,10.000000,10.000000,12.000000,9.000000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,13.000000,408.000000,0.000000,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,28.000000,10.000000,4.000000,6.000000,6.000000,2.000000,6.000000,3.000000,7.000000,9.000000,7.000000,8.000000,9.000000,9.000000,8.000000,8.000000,6.000000,8.000000,9.000000,7.000000,9.000000,9.000000,8.000000,9.000000,8.000000,7.000000,7.000000,8.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,35.000000,15.000000,16.000000,20.000000,15.000000,15.000000,40.000000,18.750000,20.000000,20.000000,15.000000,15.630000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,4.000000,25.000000,20.000000,20.000000,20.000000,15.000000,16.280000,8.00000,9.000000,9.000000,9.000000,9.000000,7.000000,3.000000,3.000000,40.000000,20.000000,20.000000,24.000000,10.000000,20.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,15.000000,15.000000,20.000000,10.000000,15.000000,38.460000,19.23000,17.390000,20.000000,15.090000,16.515000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,20.000000,20.000000,20.000000,10.000000,20.000000,37.000000,15.000000,15.000000,20.000000,10.000000,15.000000,35.000000,15.000000,15.000000,20.000000,10.000000,15.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,22.000000,552.000000,1.000000,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,1.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,8.000000,55.000000,18.000000,6.000000,10.000000,10.000000,6.000000,7.000000,7.000000,17.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,20.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,18.000000,95.000000,50.000000,40.000000,40.000000,23.810000,30.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,3.000000,80.000000,40.000000,50.000000,50.000000,20.000000,40.000000,85.000000,50.000000,40.000000,50.000000,22.220000,35.000000,100.000000,35.000000,40.000000,50.000000,35.000000,40.000000,85.000000,40.00000,30.770000,40.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.000000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [ ]:
pd.set_option('display.max_columns', None)
(df.describe())

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field_cd,race,imprace,imprelig,goal,date,go_out,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,8378.000000,8368.000000,8378.000000,8220.000000,8378.000000,8274.000000,8305.000000,8289.000000,8289.000000,8289.000000,8280.000000,8271.000000,8249.000000,8378.000000,8166.000000,8091.000000,8072.000000,8018.000000,7656.000000,7302.000000,8128.000000,8060.000000,7993.000000,8283.000000,8296.000000,8315.000000,8299.000000,8299.000000,8299.000000,8281.000000,8299.000000,8240.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8277.000000,1800.000000,8299.000000,8299.000000,8299.000000,8289.000000,8279.000000,8257.000000,6489.000000,6489.000000,6489.000000,6489.000000,6489.000000,6467.000000,8299.000000,8299.000000,8299.000000,8299.000000,8289.000000,8289.000000,8273.000000,8273.000000,8273.000000,8273.000000,8273.000000,4906.000000,4906.000000,4906.000000,4906.000000,4906.000000,8378.000000,8176.000000,8101.000000,8082.000000,8028.000000,7666.000000,7311.000000,8138.000000,8069.000000,8003.000000,7205.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,7463.000000,7463.000000,7433.000000,1984.000000,1955.000000,1984.000000,1984.000000,1955.000000,1974.000000,7445.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.00000,5775.000000,5775.000000,5775.000000,5775.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,4377.000000,4377.000000,4377.000000,4377.000000,4377.000000,3974.000000,3974.000000,3974.000000,1496.000000,668.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2016.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,8.963595,283.863767,0.164717,0.196010,0.395799,26.364999,2.756653,22.495347,17.396867,20.270759,17.459714,10.685375,11.845930,0.419551,6.190411,7.175256,7.369301,6.400599,6.778409,5.474870,6.134498,5.208251,1.960215,26.358928,7.662488,2.757186,3.784793,3.651645,2.122063,5.006762,2.158091,5.277791,6.425232,4.575491,6.245813,7.783829,6.985781,6.714544,5.737077,3.881191,5.745993,7.678515,5.304133,6.776118,7.919629,6.825401,7.851066,5.631281,4.339197,5.534131,5.570556,22.514632,17.396389,20.265613,17.457043,10.682539,11.845111,26.394360,11.071506,12.636308,15.566805,9.780089,11.014845,30.362192,13.273691,14.416891,18.422620,11.744499,11.854817,7.084733,8.294935,7.704460,8.403965,7.578388,6.941908,7.927232,8.284346,7.426213,7.617611,0.419909,6.189995,7.175164,7.368597,6.400598,6.777524,5.474559,6.134087,5.207523,0.948769,3.207814,20.791624,15.434255,17.243708,15.260869,11.144619,12.457925,7.21125,8.082000,8.257750,7.692500,7.589250,5.711510,1.843495,2.338087,32.819556,13.529923,15.293851,18.868448,7.286957,12.156028,26.217194,15.865084,17.813755,17.654765,9.913436,12.760263,26.806234,11.929177,12.103030,15.163810,9.342511,11.320866,29.344369,13.89823,13.958265,17.967233,11.909735,12.887976,7.125285,7.931529,8.238912,7.602171,7.486802,6.827964,7.394106,7.838702,7.279415,7.332191,0.780825,0.981631,0.376950,1.230615,0.934132,24.384524,16.588583,19.411346,16.233415,10.898075,12.699142,31.330357,15.654266,16.679563,16.418155,7.823909,12.207837,25.610341,10.751267,11.524839,14.276783,9.207503,11.253802,24.970936,10.923285,11.952687,14.959108,9.526191,11.966270,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,5.491068,158.584899,0.370947,0.303539,0.489051,3.563648,1.230689,12.569802,7.044003,6.782895,6.085526,6.126544,6.362746,0.493515,1.950305,1.740575,1.550501,1.954078,1.794080,2.156163,1.841258,2.129354,0.245925,3.566763,3.758935,1.230905,2.845708,2.805237,1.407181,1.444531,1.105246,3.309520,2.619024,2.801874,2.418858,1.754868,2.052232,2.263407,2.570207,2.620507,2.502218,2.006565,2.529135,2.235152,1.700927,2.156283,1.791827,2.608913,2.717612,1.734059,4.762569,12.587674,7.046700,6.783003,6.085239,6.124888,6.362154,16.297045,6.659233,6.717476,7.328256,6.998428,6.060150,16.249937,6.976775,6.263304,6.577929,6.886532,6.167314,1.395783,1.407460,1.564321,1.076608,1.778315,1.498653,1.627054,1.283657,1.779129,1.773094,0.493573,1.950169,1.740315,1.550453,1.953702,1.794055,2.156363,1.841285,2.129565,0.989889,2.444813,12.968524,6.915322,6.596420,5.356969,5.514028,5.921789,1.41545,1.455741,1.179317,1.626839,1.793136,1.820764,0.975662,0.631240,17.155270,7.977482,7.292868,8.535963,6.125187,8.241906,14.388694,6.658494,6.535894,6.129746,5.675550,6.651547,16.402836,6.401556,5.990607,7.290107,5.856329,6.296155,14.551171,6.17169,5.398621,6.100307,6.313281,5.615691,1.371390,1.503236,1.180280,1.548200,1.744634,1.411096,1.588145,1.280936,1.647478,1.521854,1.611694,1.382139,0.484683,1.294557,0.753902,13.712120,7.471537,6.124502,5.163777,5.900697,6.557041,17.551540,9.336288,7.880088,7.231325,6.100502,8.615985,17.477134,5.740351,6.004222,6.927869,6.385852,6.516178,17.007669,6.226283,7.010650,7.935509,6.403117,7.012067,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-0.830000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.00000,1.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,4.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,4.000000,154.000000,0.000000,-0.020000,0.000000,24.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,2.000000,24.000000,5.000000,2.000000,1.000000,1.000000,1.000000,4.000000,1.000000,2.000000,4.000000,2.000000,5.000000,7.000000,6.000000,5.000000,4.000000,2.000000,4.000000,7.000000,3.000000,5.000000,7.000000,5.000000,7.000000,4.000000,2.000000,5.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,10.000000,6.000000,8.000000,10.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,6.000000,10.000000,6.000000,8.000000,7.000000,8.000000,7.000000,6.000000,7.000000,8.000000,6.000000,7.000000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,14.810000,10.000000,10.000000,10.000000,7.000000,9.000000,7.00000,7.000000,8.000000,7.000000,7.000000,5.000000,1.000000,2.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,16.670000,10.000000,15.000000,15.000000,5.000000,10.000000,10.000000,8.000000,8.000000,9.000000,5.000000,7.000000,19.150000,10.00000,10.000000,15.000000,10.000000,10.000000,7.000000,7.000000,8.000000,7.000000,7.000000,6.000000,6.000000,7.000000,6.000000,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,15.220000,10.000000,16.670000,14.810000,5.000000,10.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,10.000000,7.000000,7.000000,9.000000,5.000000,7.000000,10.000000,7.000000,7.000000,9.000000,6.000000,5.000000,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,8.000000,281.000000,0.000000,0.210000,0.000000,26.000000,2.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.640000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,2.000000,26.000000,8.000000,2.000000,3.000000,3.000000,2.000000,5.000000,2.000000,6.000000,7.000000,4.000000,6.000000,8.000000,7.000000,7.000000,6.000000,3.000000,6.000000,8.000000,6.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,6.000000,4.000000,20.000000,18.180000,20.000000,18.000000,10.000000,10.640000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.000000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,0.000000,3.000000,17.650000,15.790000,18.420000,15.910000,10.000000,12.500000,7.00000,8.000000,8.000000,8.000000,8.000000,6.000000,1.000000,2.000000,30.000000,10.000000,15.000000,20.000000,5.000000,10.000000,20.000000,16.670000,19.050000,18.370000,10.000000,13.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.00000,15.000000,18.520000,10.000000,13.950000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000,0.000000,1.000000,0.000000,1.000000,1.000000,20.000000,16.670000,20.000000,16.330000,10.000000,14.290000,25.000000,15.000000,18.000000,17.000000,10.000000,10.000000,20.000000,10.000000,10.000000,12.000000,9.000000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,13.000000,408.000000,0.000000,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,28.000000,10.000000,4.000000,6.000000,6.000000,2.000000,6.000000,3.000000,7.000000,9.000000,7.000000,8.000000,9.000000,9.000000,8.000000,8.000000,6.000000,8.000000,9.000000,7.000000,9.000000,9.000000,8.000000,9.000000,8.000000,7.000000,7.000000,8.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,35.000000,15.000000,16.000000,20.000000,15.000000,15.000000,40.000000,18.750000,20.000000,20.000000,15.000000,15.630000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,4.000000,25.000000,20.000000,20.000000,20.000000,15.000000,16.280000,8.00000,9.000000,9.000000,9.000000,9.000000,7.000000,3.000000,3.000000,40.000000,20.000000,20.000000,24.000000,10.000000,20.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,15.000000,15.000000,20.000000,10.000000,15.000000,38.460000,19.23000,17.390000,20.000000,15.090000,16.515000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,20.000000,20.000000,20.000000,10.000000,20.000000,37.000000,15.000000,15.000000,20.000000,10.000000,15.000000,35.000000,15.000000,15.000000,20.000000,10.000000,15.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,22.000000,552.000000,1.000000,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,1.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,8.000000,55.000000,18.000000,6.000000,10.000000,10.000000,6.000000,7.000000,7.000000,17.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,20.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,18.000000,95.000000,50.000000,40.000000,40.000000,23.810000,30.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,3.000000,80.000000,40.000000,50.000000,50.000000,20.000000,40.000000,85.000000,50.000000,40.000000,50.000000,22.220000,35.000000,100.000000,35.000000,40.000000,50.000000,35.000000,40.000000,85.000000,40.00000,30.770000,40.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.000000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [ ]:
df.describe().round(1)

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field_cd,race,imprace,imprelig,goal,date,go_out,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.0,8377.0,8378.0,8378.0,8378.0,8378.0,8378.0,8378.0,6532.0,8378.0,8378.0,8368.0,8378.0,8220.0,8378.0,8274.0,8305.0,8289.0,8289.0,8289.0,8280.0,8271.0,8249.0,8378.0,8166.0,8091.0,8072.0,8018.0,7656.0,7302.0,8128.0,8060.0,7993.0,8283.0,8296.0,8315.0,8299.0,8299.0,8299.0,8281.0,8299.0,8240.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8299.0,8277.0,1800.0,8299.0,8299.0,8299.0,8289.0,8279.0,8257.0,6489.0,6489.0,6489.0,6489.0,6489.0,6467.0,8299.0,8299.0,8299.0,8299.0,8289.0,8289.0,8273.0,8273.0,8273.0,8273.0,8273.0,4906.0,4906.0,4906.0,4906.0,4906.0,8378.0,8176.0,8101.0,8082.0,8028.0,7666.0,7311.0,8138.0,8069.0,8003.0,7205.0,4096.0,4096.0,4096.0,4096.0,4096.0,4096.0,4000.0,4000.0,4000.0,4000.0,4000.0,7463.0,7463.0,7433.0,1984.0,1955.0,1984.0,1984.0,1955.0,1974.0,7445.0,7463.0,7463.0,7463.0,7463.0,7463.0,5775.0,5775.0,5775.0,5775.0,5775.0,5775.0,5775.0,5775.0,5775.0,5775.0,5775.0,5775.0,7463.0,7463.0,7463.0,7463.0,7463.0,4377.0,4377.0,4377.0,4377.0,4377.0,3974.0,3974.0,3974.0,1496.0,668.0,3974.0,3974.0,3974.0,3974.0,3974.0,3974.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2959.0,2959.0,2959.0,2959.0,2959.0,2959.0,2959.0,2959.0,2959.0,2959.0,2959.0,2016.0,3974.0,3974.0,3974.0,3974.0,3974.0,2016.0,2016.0,2016.0,2016.0,2016.0
mean,283.7,9.0,0.5,17.3,1.8,11.4,16.9,9.0,9.3,8.9,9.0,283.9,0.2,0.2,0.4,26.4,2.8,22.5,17.4,20.3,17.5,10.7,11.8,0.4,6.2,7.2,7.4,6.4,6.8,5.5,6.1,5.2,2.0,26.4,7.7,2.8,3.8,3.7,2.1,5.0,2.2,5.3,6.4,4.6,6.2,7.8,7.0,6.7,5.7,3.9,5.7,7.7,5.3,6.8,7.9,6.8,7.9,5.6,4.3,5.5,5.6,22.5,17.4,20.3,17.5,10.7,11.8,26.4,11.1,12.6,15.6,9.8,11.0,30.4,13.3,14.4,18.4,11.7,11.9,7.1,8.3,7.7,8.4,7.6,6.9,7.9,8.3,7.4,7.6,0.4,6.2,7.2,7.4,6.4,6.8,5.5,6.1,5.2,0.9,3.2,20.8,15.4,17.2,15.3,11.1,12.5,7.2,8.1,8.3,7.7,7.6,5.7,1.8,2.3,32.8,13.5,15.3,18.9,7.3,12.2,26.2,15.9,17.8,17.7,9.9,12.8,26.8,11.9,12.1,15.2,9.3,11.3,29.3,13.9,14.0,18.0,11.9,12.9,7.1,7.9,8.2,7.6,7.5,6.8,7.4,7.8,7.3,7.3,0.8,1.0,0.4,1.2,0.9,24.4,16.6,19.4,16.2,10.9,12.7,31.3,15.7,16.7,16.4,7.8,12.2,25.6,10.8,11.5,14.3,9.2,11.3,25.0,10.9,12.0,15.0,9.5,12.0,7.2,8.1,8.4,7.7,7.4,6.8,7.6,7.9,7.2,7.0
std,158.6,5.5,0.5,10.9,0.4,6.0,4.4,5.5,5.7,5.5,5.5,158.6,0.4,0.3,0.5,3.6,1.2,12.6,7.0,6.8,6.1,6.1,6.4,0.5,2.0,1.7,1.6,2.0,1.8,2.2,1.8,2.1,0.2,3.6,3.8,1.2,2.8,2.8,1.4,1.4,1.1,3.3,2.6,2.8,2.4,1.8,2.1,2.3,2.6,2.6,2.5,2.0,2.5,2.2,1.7,2.2,1.8,2.6,2.7,1.7,4.8,12.6,7.0,6.8,6.1,6.1,6.4,16.3,6.7,6.7,7.3,7.0,6.1,16.2,7.0,6.3,6.6,6.9,6.2,1.4,1.4,1.6,1.1,1.8,1.5,1.6,1.3,1.8,1.8,0.5,2.0,1.7,1.6,2.0,1.8,2.2,1.8,2.1,1.0,2.4,13.0,6.9,6.6,5.4,5.5,5.9,1.4,1.5,1.2,1.6,1.8,1.8,1.0,0.6,17.2,8.0,7.3,8.5,6.1,8.2,14.4,6.7,6.5,6.1,5.7,6.7,16.4,6.4,6.0,7.3,5.9,6.3,14.6,6.2,5.4,6.1,6.3,5.6,1.4,1.5,1.2,1.5,1.7,1.4,1.6,1.3,1.6,1.5,1.6,1.4,0.5,1.3,0.8,13.7,7.5,6.1,5.2,5.9,6.6,17.6,9.3,7.9,7.2,6.1,8.6,17.5,5.7,6.0,6.9,6.4,6.5,17.0,6.2,7.0,7.9,6.4,7.0,1.6,1.6,1.5,1.7,2.0,1.5,1.5,1.3,1.7,1.7
min,1.0,1.0,0.0,1.0,1.0,1.0,5.0,1.0,1.0,1.0,1.0,1.0,0.0,-0.8,0.0,18.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,18.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,3.0,2.0,2.0,1.0,3.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,3.0,1.0,4.0,3.0,2.0,1.0,1.0,1.0,10.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,4.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,3.0,2.0,1.0,2.0,2.0,4.0,1.0,1.0
25%,154.0,4.0,0.0,8.0,2.0,7.0,14.0,4.0,4.0,4.0,4.0,154.0,0.0,-0.0,0.0,24.0,2.0,15.0,15.0,17.4,15.0,5.0,9.5,0.0,5.0,6.0,6.0,5.0,6.0,4.0,5.0,4.0,2.0,24.0,5.0,2.0,1.0,1.0,1.0,4.0,1.0,2.0,4.0,2.0,5.0,7.0,6.0,5.0,4.0,2.0,4.0,7.0,3.0,5.0,7.0,5.0,7.0,4.0,2.0,5.0,2.0,15.0,15.0,17.4,15.0,5.0,9.5,10.0,6.0,8.0,10.0,5.0,7.0,20.0,10.0,10.0,15.0,6.0,10.0,6.0,8.0,7.0,8.0,7.0,6.0,7.0,8.0,6.0,7.0,0.0,5.0,6.0,6.0,5.0,6.0,4.0,5.0,4.0,0.0,2.0,14.8,10.0,10.0,10.0,7.0,9.0,7.0,7.0,8.0,7.0,7.0,5.0,1.0,2.0,20.0,10.0,10.0,10.0,0.0,5.0,16.7,10.0,15.0,15.0,5.0,10.0,10.0,8.0,8.0,9.0,5.0,7.0,19.2,10.0,10.0,15.0,10.0,10.0,7.0,7.0,8.0,7.0,7.0,6.0,6.0,7.0,6.0,6.0,0.0,0.0,0.0,1.0,1.0,15.2,10.0,16.7,14.8,5.0,10.0,20.0,10.0,10.0,10.0,0.0,5.0,10.0,7.0,7.0,9.0,5.0,7.0,10.0,7.0,7.0,9.0,6.0,5.0,7.0,7.0,8.0,7.0,6.0,6.0,7.0,7.0,6.0,6.0
50%,281.0,8.0,1.0,16.0,2.0,11.0,18.0,8.0,9.0,8.0,8.0,281.0,0.0,0.2,0.0,26.0,2.0,20.0,18.4,20.0,18.0,10.0,10.6,0.0,6.0,7.0,7.0,7.0,7.0,6.0,6.0,5.0,2.0,26.0,8.0,2.0,3.0,3.0,2.0,5.0,2.0,6.0,7.0,4.0,6.0,8.0,7.0,7.0,6.0,3.0,6.0,8.0,6.0,7.0,8.0,7.0,8.0,6.0,4.0,6.0,4.0,20.0,18.2,20.0,18.0,10.0,10.6,25.0,10.0,10.0,15.0,10.0,10.0,25.0,15.0,15.0,20.0,10.0,10.0,7.0,8.0,8.0,8.0,8.0,7.0,8.0,8.0,8.0,8.0,0.0,6.0,7.0,7.0,7.0,7.0,6.0,6.0,5.0,0.0,3.0,17.6,15.8,18.4,15.9,10.0,12.5,7.0,8.0,8.0,8.0,8.0,6.0,1.0,2.0,30.0,10.0,15.0,20.0,5.0,10.0,20.0,16.7,19.0,18.4,10.0,13.0,25.0,10.0,10.0,15.0,10.0,10.0,25.0,15.0,15.0,18.5,10.0,14.0,7.0,8.0,8.0,8.0,8.0,7.0,8.0,8.0,7.0,7.0,0.0,1.0,0.0,1.0,1.0,20.0,16.7,20.0,16.3,10.0,14.3,25.0,15.0,18.0,17.0,10.0,10.0,20.0,10.0,10.0,12.0,9.0,10.0,20.0,10.0,10.0,15.0,10.0,10.0,7.0,8.0,8.0,8.0,8.0,7.0,8.0,8.0,7.0,7.0
75%,407.0,13.0,1.0,26.0,2.0,15.0,20.0,13.0,14.0,13.0,13.0,408.0,0.0,0.4,1.0,28.0,4.0,25.0,20.0,23.8,20.0,15.0,16.0,1.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,7.0,2.0,28.0,10.0,4.0,6.0,6.0,2.0,6.0,3.0,7.0,9.0,7.0,8.0,9.0,9.0,8.0,8.0,6.0,8.0,9.0,7.0,9.0,9.0,8.0,9.0,8.0,7.0,7.0,8.0,25.0,20.0,23.8,20.0,15.0,16.0,35.0,15.0,16.0,20.0,15.0,15.0,40.0,18.8,20.0,20.0,15.0,15.6,8.0,9.0,9.0,9.0,9.0,8.0,9.0,9.0,9.0,9.0,1.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,7.0,2.0,4.0,25.0,20.0,20.0,20.0,15.0,16.3,8.0,9.0,9.0,9.0,9.0,7.0,3.0,3.0,40.0,20.0,20.0,24.0,10.0,20.0,30.0,20.0,20.0,20.0,15.0,16.7,40.0,15.0,15.0,20.0,10.0,15.0,38.5,19.2,17.4,20.0,15.1,16.5,8.0,9.0,9.0,9.0,9.0,8.0,8.0,9.0,8.0,8.0,1.0,1.0,1.0,1.0,1.0,30.0,20.0,20.0,20.0,15.0,16.7,40.0,20.0,20.0,20.0,10.0,20.0,37.0,15.0,15.0,20.0,10.0,15.0,35.0,15.0,15.0,20.0,10.0,15.0,8.0,9.0,9.0,9.0,9.0,8.0,9.0,9.0,8.0,8.0
max,552.0,22.0,1.0,44.0,2.0,21.0,22.0,22.0,22.0,22.0,22.0,552.0,1.0,0.9,1.0,55.0,6.0,100.0,60.0,50.0,50.0,53.0,30.0,1.0,10.5,10.0,10.0,11.0,10.0,10.0,10.0,10.0,8.0,55.0,18.0,6.0,10.0,10.0,6.0,7.0,7.0,17.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,14.0,10.0,13.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,20.0,100.0,60.0,50.0,50.0,53.0,30.0,95.0,35.0,35.0,45.0,50.0,40.0,100.0,50.0,40.0,50.0,50.0,30.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,8.0,18.0,95.0,50.0,40.0,40.0,23.8,30.0,10.0,10.0,10.0,10.0,10.0,10.0,3.0,3.0,80.0,40.0,50.0,50.0,20.0,40.0,85.0,50.0,40.0,50.0,22.2,35.0,100.0,35.0,40.0,50.0,35.0,40.0,85.0,40.0,30.8,40.0,50.0,30.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,21.0,9.0,1.0,9.0,4.0,80.0,65.0,45.0,30.0,30.0,55.0,80.0,60.0,45.0,40.0,30.0,55.0,80.0,40.0,30.0,30.0,40.0,45.0,80.0,50.0,60.0,40.0,50.0,45.0,12.0,12.0,12.0,12.0,12.0,10.0,10.0,10.0,10.0,10.0

In [ ]:
for colonne in df.columns:
    valeurs_uniques = df[colonne].unique()
    print(f"Valeurs uniques de la colonne '{colonne}':")
    print(valeurs_uniques)
    print()

Valeurs uniques de la colonne 'iid':
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199
 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253
 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271
 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289
 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307
 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325
 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343
 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361
 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379
 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397
 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415
 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433
 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451
 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469
 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487
 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505
 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523
 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541
 542 543 544 545 546 547 548 549 550 551 552]

Valeurs uniques de la colonne 'id':
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 19.
 20. 18. 21. 22. nan]

Valeurs uniques de la colonne 'gender':
[0 1]

Valeurs uniques de la colonne 'idg':
[ 1  3  5  7  9 11 13 15 17 19  2  4  6  8 10 12 14 16 18 20 21 23 25 27
 29 31 33 34 35 22 24 26 28 30 32 36 37 39 38 40 41 42 43 44]

Valeurs uniques de la colonne 'condtn':
[1 2]

Valeurs uniques de la colonne 'wave':
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]

Valeurs uniques de la colonne 'round':
[10 16 19 18  5 20  9 21 14  8  6 11 15  7 22]

Valeurs uniques de la colonne 'position':
[ 7  3  9  6  4  8  5 10  1  2 12 13 15 18 19 17 11 14 16 20 21 22]

Valeurs uniques de la colonne 'positin1':
[nan  2.  3.  4.  1.  5.  9. 10. 13. 14.  8.  6. 12. 11. 15.  7. 16. 19.
 18. 17. 20. 21. 22.]

Valeurs uniques de la colonne 'order':
[ 4  3 10  5  7  6  1  2  8  9 11 15 12 16 13 14 18 17 19 20 21 22]

Valeurs uniques de la colonne 'partner':
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 19 20 18 21 22]

Valeurs uniques de la colonne 'pid':
[ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.   1.   2.   3.   4.
   5.   6.   7.   8.   9.  10.  40.  41.  42.  43.  44.  45.  46.  47.
  48.  49.  50.  51.  52.  53.  54.  55.  21.  22.  23.  24.  25.  26.
  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  66.
  67.  68.  69.  70.  71.  72.  73.  74.  75.  56.  57.  58.  59.  60.
  61.  62.  63.  64.  65.  94.  95.  96.  97.  98.  99. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 110. 111.  76.  77.  78.  79.  80.
  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93. 122.
 123. 124. 125. 126. 127. 128. 129. 130. 131. 112. 113. 114. 115. 116.
 117. 119. 120. 121.  nan 137. 138. 139. 140. 141. 132. 133. 134. 135.
 136. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167. 168. 169. 170.
 171. 172. 173. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152.
 153. 154. 155. 156. 157. 184. 185. 186. 187. 188. 189. 190. 191. 192.
 193. 174. 175. 176. 177. 178. 179. 180. 181. 182. 183. 214. 215. 216.
 217. 218. 219. 220. 221. 222. 223. 224. 225. 226. 227. 228. 229. 230.
 231. 232. 233. 194. 195. 196. 197. 198. 199. 200. 201. 202. 203. 204.
 205. 206. 207. 208. 209. 210. 211. 212. 213. 243. 244. 245. 246. 247.
 248. 249. 250. 251. 234. 235. 236. 237. 238. 239. 240. 241. 242. 273.
 274. 275. 276. 277. 278. 279. 280. 281. 282. 283. 284. 285. 286. 287.
 288. 289. 290. 291. 292. 293. 252. 253. 254. 255. 256. 257. 258. 259.
 260. 261. 262. 263. 264. 265. 266. 267. 268. 269. 270. 271. 272. 308.
 309. 310. 311. 312. 313. 314. 315. 316. 317. 318. 319. 320. 321. 294.
 295. 296. 297. 298. 299. 300. 301. 302. 303. 304. 305. 306. 307. 332.
 333. 334. 335. 336. 337. 338. 339. 340. 322. 323. 324. 325. 326. 327.
 328. 329. 330. 331. 361. 362. 363. 364. 365. 366. 367. 368. 369. 370.
 371. 372. 373. 374. 375. 376. 377. 378. 341. 342. 343. 344. 345. 346.
 347. 348. 349. 350. 351. 352. 353. 354. 355. 356. 357. 358. 359. 360.
 397. 398. 399. 400. 401. 402. 403. 404. 405. 406. 407. 408. 409. 410.
 411. 412. 413. 414. 415. 379. 380. 381. 382. 383. 384. 385. 386. 387.
 388. 389. 390. 391. 392. 393. 394. 395. 396. 422. 423. 424. 425. 426.
 427. 428. 429. 416. 417. 418. 419. 420. 421. 440. 441. 442. 443. 444.
 445. 446. 447. 448. 449. 450. 451. 452. 453. 430. 431. 432. 433. 434.
 435. 436. 437. 438. 439. 460. 461. 462. 463. 464. 465. 454. 455. 456.
 457. 458. 459. 481. 482. 483. 484. 485. 486. 487. 488. 489. 490. 491.
 492. 493. 494. 495. 466. 467. 468. 469. 470. 471. 472. 473. 474. 475.
 476. 477. 478. 479. 480. 502. 503. 504. 505. 506. 507. 508. 496. 497.
 498. 499. 500. 501. 531. 532. 533. 534. 535. 536. 537. 538. 539. 540.
 541. 542. 543. 544. 545. 546. 547. 548. 549. 550. 551. 552. 509. 510.
 511. 512. 513. 514. 515. 516. 517. 518. 519. 520. 521. 522. 523. 524.
 525. 526. 527. 528. 529. 530.]

Valeurs uniques de la colonne 'match':
[0 1]

Valeurs uniques de la colonne 'int_corr':
[ 0.14  0.54  0.16  0.61  0.21  0.25  0.34  0.5   0.28 -0.36  0.29  0.18
  0.1  -0.21  0.32  0.73  0.6   0.07  0.11  0.39 -0.24 -0.14  0.09 -0.04
 -0.3  -0.26 -0.15 -0.47 -0.18  0.05  0.37  0.35  0.15 -0.19 -0.43  0.
 -0.17  0.08 -0.16  0.06 -0.05 -0.13 -0.06  0.33 -0.51  0.12  0.19  0.47
  0.03  0.46  0.43  0.52 -0.46 -0.27  0.59  0.31 -0.34 -0.03 -0.11  0.42
 -0.4  -0.23  0.17  0.68 -0.01 -0.35  0.3   0.65  0.24  0.41  0.49  0.01
  0.22 -0.08  0.27  0.44  0.62 -0.2  -0.02 -0.33 -0.52 -0.1   0.58 -0.57
 -0.31 -0.07 -0.32  0.04 -0.12  0.48 -0.22 -0.29  0.38  0.53 -0.38  0.02
 -0.28  0.13  0.2    nan -0.41 -0.44  0.51 -0.48  0.4   0.26  0.77 -0.49
 -0.25 -0.09  0.45 -0.39  0.83  0.57 -0.61  0.72 -0.37  0.23 -0.58  0.8
 -0.56  0.63 -0.63  0.71  0.36  0.56  0.55  0.76  0.69  0.79  0.9   0.67
  0.66  0.81  0.64  0.74  0.75  0.85 -0.42 -0.5  -0.59  0.7   0.82  0.78
 -0.45 -0.83  0.88 -0.7  -0.62 -0.55  0.87  0.91  0.84 -0.64 -0.73 -0.54]

Valeurs uniques de la colonne 'samerace':
[0 1]

Valeurs uniques de la colonne 'age_o':
[27. 22. 23. 24. 25. 30. 28. 21. 26. 29. nan 39. 32. 34. 35. 18. 20. 19.
 37. 33. 36. 31. 42. 38. 55.]

Valeurs uniques de la colonne 'race_o':
[ 2.  4.  3.  6.  1. nan]

Valeurs uniques de la colonne 'pf_o_att':
[ 35.    60.    19.    30.    50.    33.33 100.    15.    45.    20.
  10.     9.09  25.    40.    12.    17.      nan  21.     5.    18.
  14.    80.    17.39  18.75  18.6   20.83  16.67  12.77   6.67  18.18
  19.05  15.91  16.    15.22  20.51  27.78  11.11  17.78  16.28  19.57
  18.37  14.29   8.33  11.36  15.09   8.51  14.55   9.76  15.38  16.98
  19.44  15.56  20.45  20.93   9.52  12.24  13.04  19.15  16.07  17.02
  14.89   7.5   21.28  17.24  14.71  25.64  13.51  21.43  23.81  17.65
  17.5   13.21  19.61  14.58  17.31  11.54  16.36  15.52  22.    90.
  24.    27.    23.     0.     7.     2.    31.58  75.     9.    70.
  95.     8.    55.    28.    58.  ]

Valeurs uniques de la colonne 'pf_o_sin':
[20.    0.   18.    5.   10.   15.   11.11 25.   18.18 35.     nan 22.
 23.   17.    7.   30.    8.   24.   32.   21.    3.   40.   17.39 16.67
 16.28 20.83 19.15 22.73 19.05 20.45 18.75 15.22 23.08 12.5  19.44 13.95
 17.78 20.93 10.87 18.37 14.29 16.   16.98 16.36 19.51 17.31 18.87 16.33
 15.09 19.57 23.81 20.41 21.74 21.28 19.23 17.86 22.5  17.5  17.02  5.13
 17.24 14.71 17.95 18.92 17.65 15.69 13.46 15.56 19.    2.   14.   13.
 47.   60.   12.   14.53 10.53  1.   26.  ]

Valeurs uniques de la colonne 'pf_o_int':
[20.    0.   19.   15.   30.   25.   11.11 35.   27.27 10.   40.   18.
   nan 50.   23.   22.   45.   17.   21.    5.   15.22 18.75 18.6  16.67
 17.02 18.18 19.05 20.45 19.57 20.51 20.83 19.44 17.78 22.22 20.41 21.43
 16.   22.73 16.98 19.15 19.51 17.31 18.87 16.33 23.26 17.39 19.23 17.86
 17.5  21.28 23.08 23.81 17.24 14.71 15.38 21.62 17.65 18.37  2.   28.
 42.86 24.79 15.79 27.    1.    8.  ]

Valeurs uniques de la colonne 'pf_o_fun':
[20.   40.   18.   10.   11.11  0.   15.   25.   18.18 30.   16.     nan
 22.   17.   19.   23.   12.    5.   24.   35.   17.39 20.83 18.6  16.67
 17.02 17.78 13.64 19.05 20.45 18.75 17.95 27.78 16.28 15.56 19.57 20.41
 21.43 14.58 18.87 19.15 14.   14.63 17.31 16.98 18.37 14.29 19.23 17.86
 22.5  21.28 12.77 12.82 17.24 14.71 20.51 13.51 23.81 23.26 15.69 12.5
 16.33  2.    9.52  8.   17.09 21.05 27.   50.    3.    1.   45.   13.  ]

Valeurs uniques de la colonne 'pf_o_amb':
[ 0.   14.    5.   10.   11.11 15.   18.18 16.   20.   25.     nan  7.
 53.    8.   17.   13.    6.   11.    2.   18.   12.   13.04  6.67 12.5
 11.63  6.25 16.67 14.89 13.64  9.52 11.36 18.75  2.56  2.78 16.28 17.78
 15.56 13.95 19.57 16.33 19.05 18.87 19.15 16.36 19.51 17.31 16.98 18.37
 13.21 13.33 15.22 20.41 12.77 13.46 17.86  6.38 17.95 14.81  4.76 10.87
 13.79 20.59 10.26 13.51 11.9   2.38  2.33 15.69  9.62 15.38 17.65 11.54
 19.23 17.24 19.    4.   14.29  3.    5.98 10.53 30.    1.    9.  ]

Valeurs uniques de la colonne 'pf_o_sha':
[ 5.    0.   12.   20.   10.   22.22 15.    9.09 18.     nan 13.   14.
 22.    8.   30.   25.    6.    2.   19.57 13.33 12.5  16.28 18.75 16.67
 19.15 15.56 13.64 14.29 11.36 16.    8.33 15.38  2.78 17.78 11.63 10.87
  6.67  6.12  9.52 18.18 13.21 14.89 16.36 17.07 16.33 15.09 11.11 16.98
  2.27 13.04 17.39 12.77 17.31 11.54  7.5   8.51 10.64 21.28 20.51 18.52
 23.81 15.22 17.24 20.59 10.26 18.92 11.9   2.38 13.46 15.69 19.23 13.73
 14.55 15.52 21.    7.62 11.    1.   17.09 10.53 17.    9.    7.   19.
  3.    4.  ]

Valeurs uniques de la colonne 'dec_o':
[0 1]

Valeurs uniques de la colonne 'attr_o':
[ 6.   7.  10.   8.   3.   9.   5.   4.   2.   1.   nan  0.   6.5  7.5
  8.5  9.5  9.9 10.5  3.5]

Valeurs uniques de la colonne 'sinc_o':
[ 8.  10.   7.   6.   9.   3.   5.   4.   1.   2.   nan  4.5  8.5  0.
  7.5]

Valeurs uniques de la colonne 'intel_o':
[ 8.  10.   9.   7.   5.   6.   4.   3.   1.   nan  2.   6.5  0.   8.5
  7.5  9.5  2.5  5.5]

Valeurs uniques de la colonne 'fun_o':
[ 8.   7.  10.   6.   5.   9.   3.   4.   1.   2.   nan  5.5  0.   6.5
  9.5  7.5  8.5 11. ]

Valeurs uniques de la colonne 'amb_o':
[ 8.   7.  10.   9.   6.   5.   nan  4.   1.   2.   3.   5.5  9.5  0.
  7.5  8.5]

Valeurs uniques de la colonne 'shar_o':
[ 6.   5.  10.   8.   7.   9.   4.   3.   nan  1.   2.   0.   7.5  6.5
  8.5  5.5]

Valeurs uniques de la colonne 'like_o':
[ 7.   8.  10.   2.   6.5  6.   9.   4.   5.   3.   1.   8.5  9.5  nan
  7.5  4.5  0.   5.5  9.7]

Valeurs uniques de la colonne 'prob_o':
[ 4.  10.   7.   6.   1.   5.   8.   2.   3.   9.   nan  4.5  6.5  5.5
  0.   7.5  8.5  9.5  3.5  1.5]

Valeurs uniques de la colonne 'met_o':
[ 2.  1. nan  3.  5.  6.  7.  8.]

Valeurs uniques de la colonne 'age':
[21. 24. 25. 23. 22. 26. 27. 30. 28. nan 29. 34. 35. 32. 39. 20. 19. 18.
 37. 33. 36. 31. 42. 38. 55.]

Valeurs uniques de la colonne 'field':
['Law' 'law' 'Economics' 'Masters in Public Administration'
 'Masters of Social Work&Education' 'Finance' 'Business'
 'political science' 'money' 'Operations Research' 'TC (Health Ed)'
 'Psychology' 'social work' 'Social Work' 'Speech Language Pathology'
 'Speech Languahe Pathology' 'Educational Psychology'
 'Applied Maths/Econs' 'Mathematics' 'Statistics'
 'Organizational Psychology' 'Mechanical Engineering' 'Finanace'
 'Finance&Economics' 'Undergrad - GS' 'Mathematical Finance' 'Medicine'
 'MBA' 'LAW' nan 'psychology' 'German Literature'
 'Business & International Affairs' 'MFA Creative Writing' 'Engineering'
 'Electrical Engineering' 'Classics' 'Operations Research (SEAS)'
 'chemistry' 'Journalism' 'Elementary/Childhood Education (MA)'
 'microbiology' 'Masters of Social Work' 'Communications' 'Marketing'
 'Chemistry' 'International Educational Development'
 'Education Administration' 'Business (MBA)' 'Computer Science'
 'Climate-Earth and Environ. Science' 'financial math' 'Business- MBA'
 'Religion' 'Film' 'Sociology' 'Economics, English' 'Economics, Sociology'
 'Polish' 'English' 'psychology and english' 'Biomedical Engineering'
 'Economics and Political Science' 'Art History/medicine' 'philosophy'
 'electrical engineering' 'marine geophysics' 'theory' 'engineering'
 'Nutrition/Genetics' 'Neuroscience' 'Comparative Literature'
 'International Relations' 'History of Religion'
 'international affairs - economic development' 'Political Science'
 'Modern Chinese Literature' 'business' 'Business, marketing'
 'physics (astrophysics)' 'Physics' 'Business/ Finance/ Real Estate'
 'Biochemistry' 'Art Education' 'Philosophy' 'American Studies (Masters)'
 'biology' 'Cell Biology' 'Microbiology' 'math'
 'International Affairs/Finance' 'International Affairs'
 'international affairs/international finance' 'Health policy'
 'English and Comp Lit' 'international finance and business'
 'Sociomedical Sciences- School of Public Health' 'Epidemiology'
 'Social work' 'International Business' 'Medical Informatics'
 'International Finance, Economic Policy' 'Law and Social Work'
 'International Development' 'Business/Law' 'Clinical Psychology'
 'Religion, GSAS' 'International Affairs and Public Health'
 'International affairs' 'History'
 'Business and International Affairs (MBA/MIA Dual Degree)' 'QMSS'
 'climate change' 'Public Administration' 'MA Biotechnology'
 'International Affairs/Business' 'Ecology'
 'Master in Public Administration' 'Computational Biochemsistry'
 'Neurobiology' 'Mathematics, PhD' 'History (GSAS - PhD)' 'biomedicine'
 'Master of International Affairs' 'Sociology and Education'
 'elementary education' 'Biology' 'American Studies' 'Arts Administration'
 'Conservation biology' 'sociology' 'Japanese Literature' 'biotechnology'
 'Earth and Environmental Science' 'Philosophy (Ph.D.)'
 'Philosophy and Physics' 'nutrition' 'MA Science Education' 'Genetics'
 'Law and English Literature (J.D./Ph.D.)' 'french' 'Nutritiron'
 'GS Postbacc PreMed' 'Art History' 'Molecular Biology'
 'Genetics & Development' 'medical informatics' 'Electrical Engg.'
 'Business School' 'International Politics'
 'MBA / Master of International Affairs (SIPA)' 'genetics'
 'medicine and biochemistry' 'Social Studies Education'
 'MA Teaching Social Studies' 'Education Policy'
 'Education- Literacy Specialist' 'Anthropology/Education'
 'bilingual education' 'speech pathology' 'Education' 'Speech Pathology'
 'math education' 'TESOL' 'Elementary Education'
 'Cognitive Studies in Education' 'education' 'Finance/Economics'
 'Museum Anthropology' 'Environmental Engineering'
 'Business Administration' 'Curriculum and Teaching/Giftedness'
 'Anthropology' 'Instructional Tech & Media' 'School Psychology'
 'Instructional Media and Technology' 'SIPA / MIA' 'English Education'
 'art education' 'MA in Quantitative Methods' 'Early Childhood Education'
 'anthropology' 'Architecture' 'Urban Planning'
 'Ed.D. in higher education policy at TC'
 'International Security Policy - SIPA' 'Nutrition' 'EDUCATION'
 'Applied Physiology & Nutrition' 'music education' 'Music Education'
 'Counseling Psychology' 'Communications in Education'
 'Intellectual Property Law' 'MBA Finance' 'Intrernational Affairs'
 'BUSINESS CONSULTING' 'business school' 'Business, Media' 'MFA -Film'
 'Higher Ed. - M.A.' 'Neuroscience and Education' 'Creative Writing'
 'Creative Writing - Nonfiction' 'Writing: Literary Nonfiction'
 'Creative Writing (Nonfiction)' 'NonFiction Writing'
 'Theatre Management & Producing' 'Financial Engineering'
 'biomedical engineering' 'Fundraising Management'
 'Business (Finance & Marketing)' 'Elementary Education - Preservice'
 'Education Leadership - Public School Administration' 'MFA Writing'
 'Bilingual Education' 'International Affairs - Economic Policy'
 'SIPA - Energy' 'Public Policy' 'Law/Business' 'MFA  Poetry'
 'SOA -- writing' 'biomedical informatics' 'physics' 'art history'
 'working' 'Consulting' 'Human Rights: Middle East' 'Human Rights'
 'medicine' 'Biotechnology' 'SIPA-International Affairs'
 'teaching of English' 'GSAS' 'African-American Studies/History'
 'Neurosciences/Stem cells' 'film' 'journalism' 'Theater' 'Biology PhD'
 'biochemistry/genetics' 'epidemiology' 'Stats' 'math of finance'
 'MFA Acting Program' 'Nonfiction writing'
 'Biochemistry & Molecular Biophysics' 'Acting' 'Social Work/SIPA'
 'Public Health' 'ELECTRICAL ENGINEERING' 'Math' 'Biomedical engineering'
 'Industrial Engineering' 'Industrial Engineering/Operations Research'
 'Masters of Industrial Engineering' 'Biomedical Informatics'
 'MBA - Private Equity / Real Estate' 'General management/finance'
 'Climate Dynamics']

Valeurs uniques de la colonne 'field_cd':
[ 1.  2. 13.  8.  5.  9.  3. 11. nan 12.  4.  7.  6. 10. 14. 16. 15. 17.
 18.]

Valeurs uniques de la colonne 'undergra':
[nan 'George Mason University' 'Holy Cross' 'University of Pennsylvania'
 'UCLA' 'Swarthmore College' 'Columbia College' 'SUNY Binghamton'
 'Barnard College' 'school of social sciences in uruguay'
 'Yale University' 'University of Washington' 'Columbia'
 'SUNY Stony Brook' 'Fudan University, Shanghai, China' 'Cornell'
 'Universidad Catolica de Chile' 'Amherst College' 'Hebrew University'
 'Universidad Iberoamericana' "Tokyo Woman's Christian University, Japan"
 'University of Maryland, and Oxford' 'UW Madison' 'Harvard'
 'Syracuse University' 'Rice' 'Smith College' 'Brown University'
 'University of Warsaw' 'Yale' 'Columbia University' 'Stanford'
 'colby college, waterville, me' 'ChungShenMedicalUniversity(Taiwan)'
 'Wesleyan University' 'University of Toronto' 'Brandeis University'
 'PACE University' 'charles university, prague, czech republic'
 'UC Berkeley' 'Novosibirsk State University' 'RPI' 'umass' 'UNLV'
 'MSU, Russia' 'University of North Carolina at Charlotte' 'REC, Rourkela'
 'Columbia Business School' 'tech school' 'Queens College'
 'Connecticut College' 'Emory University' 'Harvey Mudd College (Physics)'
 'University of Paris' 'U of  Michigan' 'MIT' 'Rutgers University'
 'Arizona State' 'Univ of Pennsylvania' 'Washington U. in St. Louis'
 'SUNY Geneseo' 'New York University' 'Miami University'
 'university of pennsylvania' 'marymount manhattan college'
 'Holy Cross College' 'university of the philippines'
 'National Taiwan University' 'William and Mary' 'Taiwan University'
 'SUNY Albany' 'UPenn' 'Brown' 'Delhi University' 'Princeton U.'
 'Engineering' 'Harcourt Butler Technological Institute'
 'Penn State University' 'UC Davis' "Ecole Superieure d'Electricite"
 'Kunitachi College of Music (in Japan)'
 'Fu Jen Catholic University, Taiwan' 'Bucknell University'
 'Fordham University' 'University of Arizona' 'Binghamton University'
 'Cal Berkeley' 'Univ. of Connecticut' 'university of wisconsin/la crosse'
 'Cornell University' 'Trinity College' 'Georgetown University'
 'Florida International University' 'Texas A&M'

In [ ]:
#Maintenant que le dataset est propre nous allons analyser et comparer les données entre elles

In [ ]:
# Calculer le nombre d'hommes et de femmes
nombre_hommes = df['gender'].value_counts().get(1, 0)
nombre_femmes = df['gender'].value_counts().get(0, 0)

# Afficher les résultats
print(f"Nombre d'hommes : {nombre_hommes}")
print(f"Nombre de femmes : {nombre_femmes}")

Nombre d'hommes : 4194
Nombre de femmes : 4184

In [ ]:
#On calcule la moyenne de partenaires recontrés dans une sessions

In [ ]:
moyenne_rencontre_session = df['round'].mean().round(1)
print(moyenne_rencontre_session)

16.9

In [ ]:
# Calculer le nombre de matchs et de non-matchs
nombre_de_matchs = df['match'].value_counts().get(1, 0)
nombre_de_non_matchs = df['match'].value_counts().get(0, 0)

# Afficher les résultats
print("Nombre de matchs : ", nombre_de_matchs)
print("Nombre de non-matchs : ", nombre_de_non_matchs)

Nombre de matchs :  1380
Nombre de non-matchs :  6998

In [ ]:
# Calculer le nombre de personnes étant de la même ethnie
idem_ethnie = df['samerace'].value_counts().get(1, 0)
diff_ethnie = df['samerace'].value_counts().get(0, 0)

# Afficher les résultats
print("Personne de la même ethnie : ", idem_ethnie)
print("Personne d'une ethnie différente : ", diff_ethnie)

Personne de la même ethnie :  3316
Personne d'une ethnie différente :  5062

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Columns: 195 entries, iid to amb5_3
dtypes: float64(174), int64(13), object(8)
memory usage: 12.5+ MB

In [ ]:
df["age_o"].replace(' ', np.nan).astype

<bound method NDFrame.astype of 0       27.0
1       22.0
2       22.0
3       23.0
4       24.0
        ...
8373    26.0
8374    24.0
8375    29.0
8376    22.0
8377    22.0
Name: age_o, Length: 8378, dtype: float64>

In [ ]:
#Retirer et remplacer les valeurs nulles
df["age_o"]=pd.to_numeric(df["age_o"],errors="coerce")

In [ ]:
df["age_o"].value_counts(dropna=False)

27.0    1059
23.0     894
26.0     869
24.0     863
25.0     837
28.0     746
22.0     651
29.0     589
30.0     574
21.0     289
32.0     210
33.0     161
34.0     152
31.0     125
NaN      104
35.0      60
20.0      54
36.0      45
42.0      20
19.0      19
38.0      19
39.0      18
18.0       9
55.0       6
37.0       5
Name: age_o, dtype: int64

In [ ]:
#calcul de la moyenne d'age, de l'âge min et de l'age max
df["age_o"].mean().round(1)

26.4

In [ ]:
df["age_o"].max()

55.0

In [ ]:
df["age_o"].min()

18.0

In [ ]:
#calculer la moyenne, la note max et la note min donné aux participants
df["attr_o"].describe().round(1)

count    8166.0
mean        6.2
std         2.0
min         0.0
25%         5.0
50%         6.0
75%         8.0
max        10.5
Name: attr_o, dtype: float64